### ISSUE TITLE
Ошибка при логировании.

### ISSUE THREAD

**Issue by raywave** [TGXed/CocosCore#4]
При запуске бота с указанием logsDirectory вылезает ошибка о несуществующем файле для логирования.

> Error: ENOENT: no such file or directory, open './logs/12.11.2019 10:57:16.txt'

**Comment by tangenx** [comment]
Возможно, неверно указан путь к папке.

**Comment by raywave** [comment]
> Возможно, неверно указан путь к папке.

Путь к папке указан верно, папка создана, с помощью fs индексируется, абсолютно та же история, если папки не существует.

Путь я проверил первым делом, с помощью fs.appendFileSync индексируется нормально, однако в боте выдает ошибку.

> logsDirectory: './logs',

После небольшого дебаггинга, для себя я пришел к выводу, что fs отказывается записывать файл из-за наличия ':' в пути, что получается из

> Utils.getTimeString

Если убрать ':', (для дебаггинга в пути в index.js добавил к `${Utils.getTimeString()` `.replace(/:/g, ''`),) то всё заработает. (`./logs/13.11.2019 23:08:53.txt` -> `./logs/13.11.2019 230853.txt`)

Насчет фикса - либо убрать ':' во времени, либо каким-либо образом escape'ить их, но тут понятия не имею.
