### ISSUE TITLE
Command Not Found Handler

### ISSUE THREAD

**Issue by raywave** [TGXed/CocosCore#6]
Хотелось бы видеть реализацию обработчика сообщений, если команда не найдена.

**Comment by bit0r1n** [comment]
https://github.com/TGXed/CocosCore/blob/master/src/messages/messageHandler.js#L132

**Comment by raywave** [comment]
> https://github.com/TGXed/CocosCore/blob/master/src/messages/messageHandler.js#L132

Мне хотелось бы видеть его модификацию его без изменения модуля.

**Comment by bit0r1n** [comment]
автор пока придерживается только такого метода (пр. команда чат-бота)
